####################
# EXAMPLE TEMPLATE #
####################

action1:
  type: "app"
  name: "Notepad++"
  path: 'C:\Programy\Notepad++\notepad++.exe'

action2:
  type: "sleep"
  value: 1

action3:
  type: "keystroke"
  sequence:
    - type: "series"
      value: ["/", "tab", "/"]
    - type: "parallel"
      value: ["ctrl", "s"]
